[package]
name = "pebble-server"
version = "0.1.0"
authors = ["Lukáš Hozda <luk.hozda@gmail.com>"]

[dependencies]
serde = "^1.0.4"
serde_derive = "^1.0.4"
toml = "^0.4.1"
ansi_term = "^0.9.0"
serde_cbor = "*"
lazy_static = "*"
version-compare = "0.0.4"
